# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # Configure
  _instanceof:
    ToDo\Shared\Domain\Bus\Event\DomainEventSubscriber:
      tags: [ 'app.domain_event_subscriber' ]

    ToDo\Shared\Domain\Bus\Command\CommandHandler:
      tags: [ 'app.command_handler' ]

    ToDo\Shared\Domain\Bus\Query\QueryHandler:
      tags: [ 'app.query_handler' ]

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  #  App\:
  #    resource: '../src/'
  #    exclude:
  #      - '../src/DependencyInjection/'
  #      - '../src/Kernel.php'

  App\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  ToDo\:
    resource: '../../src/'


  # -- TAGGING --
  ToDo\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
    arguments: [ !tagged app.domain_event_subscriber ]
    lazy: true

  ToDo\Shared\Infrastructure\Bus\Event\DomainEventMapping:
    arguments: [ !tagged app.domain_event_subscriber ]

  ToDo\Shared\Infrastructure\Bus\Event\DomainEventSubscriberLocator:
    arguments: [ !tagged app.domain_event_subscriber ]

  ToDo\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

#  ToDo\Shared\Infrastructure\Symfony\BasicHttpAuthMiddleware:
#    tags:
#      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

#  ToDo\Shared\Infrastructure\Symfony\ApiExceptionListener:
#    tags:
#      - { name: kernel.event_listener, event: kernel.exception, method: onException }
#

  # -- APP DEFINITIONS --
  # Command/Query Handlers
  ToDo\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus:
    arguments: [ !tagged app.command_handler ]

  ToDo\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus:
    arguments: [ !tagged app.query_handler ]

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  ToDo\Shared\Infrastructure\Elasticsearch\ElasticsearchClient:
    factory: '@ToDo\Shared\Infrastructure\Elasticsearch\ElasticsearchClientFactory'
    arguments:
      - '%env(ELASTICSEARCH_HOST)%'
      - '%env(ELASTICSEARCH_INDEX_PREFIX)%'
      - '%kernel.project_dir%/etc/databases/elasticsearch'
      - '%env(APP_ENV)%'
    public: true


  ToDo\ToDo\Domain\ToDoRepository: '@ToDo\ToDo\Infrastructure\Repository\ElasticsearchToDoRepository'
#  ToDo\ToDo\Domain\ToDoRepository: '@ToDo\ToDo\Infrastructure\Repository\DummyToDoRepository'
